apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sd2660-devops
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/backend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/backend.image: "495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/backend"
    argocd-image-updater.argoproj.io/frontend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/frontend.image: "495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/frontend"
spec:
  project: default
  destination:
    namespace: app-argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/nhatbao47/sd2660_k8s_chart'
    targetRevision: HEAD
    path: '.'
    helm:
      values: |
        backend:
          image:
            repository: 495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/backend
            tag: "17"
        frontend:
          image:
            repository: 495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
            tag: "17"
        mongo:
          image:
            repository: mongo
            tag: "latest"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
