apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  log.level: debug
  repositories: |
    - name: "ecr-repository"
      type: "ecr"
      url: "https://495016266100.dkr.ecr.ap-southeast-1.amazonaws.com"
      insecure: false
  images: |
    - name: "495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/backend"
      updates:
        - strategy: "latest"
    - name: "495016266100.dkr.ecr.ap-southeast-1.amazonaws.com/frontend"
      updates:
        - strategy: "latest"
