apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  selector:
    name: {{ .Values.mongo.name }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      protocol: TCP
      targetPort: {{ .Values.mongo.service.targetPort }}
  type: {{ .Values.mongo.service.type }}
